export { default as About } from './about.svg';
export { default as Articles } from './article.svg';
export { default as Calendar } from './calendar.svg';
export { default as Copy } from './copy.svg';
export { default as Main } from './main.svg';
export { default as Profile } from './profle.svg';
export { default as ThemeDark } from './theme-dark.svg';
export { default as ThemeLight } from './theme-light.svg';
export { default as ViewEye } from './view-eye.svg';
